const characters = {
	poqun_jiyi: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["rixun", "moyu", "yuyu"],
		img: "extension/破群杀/image/jiyi.jpg",
	},
	poqun_xiaoche: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["tuhao", "ziyi", "guangming"],
		img: "extension/破群杀/image/xiaoche.jpg",
	},
	poqun_xiaoqi: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["maihao", "shenyin"],
		img: "extension/破群杀/image/xiaoqi.jpg",
	},
	poqun_lingxin: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["ruoji", "jiche"],
		img: "extension/破群杀/image/lingxin.jpg",
	},
	poqun_dadi: {
		sex: "male",
		group: "shu",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["bianlu", "daifa"],
		img: "extension/破群杀/image/dadi.jpg",
	},
	poqun_peipei: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["caishang", "shenzao", "yuefeng"],
		img: "extension/破群杀/image/peipei.jpg",
	},
	poqun_fengjie: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["poqun_fugui", "poqun_lingfeng"],
		img: "extension/破群杀/image/fengjie.jpg",
	},
};

export default characters;
