const characters = {
	poqun_jiyi: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["poqun_rixun", "poqn_touxian", "poqun_yishen"],
		img: "extension/破群杀/image/jiyi.jpg",
	},
	poqun_xiaoche: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["poqun_leshi", "poqun_ziyu", "poqun_quuan"],
		img: "extension/破群杀/image/xiaoche.jpg",
	},
	poqun_xiaoqi: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["poqun_zhuanjie", "poqun_qianzong"],
		img: "extension/破群杀/image/xiaoqi.jpg",
	},
	poqun_lingxin: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["poqun_cangfeng", "poqun_huifeng"],
		img: "extension/破群杀/image/lingxin.jpg",
	},
	poqun_dadi: {
		sex: "male",
		group: "shu",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["poqun_bianlu", "poqun_daifa"],
		img: "extension/破群杀/image/dadi.jpg",
	},
	// poqun_peipei: {
	// 	sex: "female",
	// 	group: "qun",
	// 	hp: 3,
	// 	maxHp: 3,
	// 	hujia: 0,
	// 	skills: ["poqun_yucheng", "poqun_quanduan", "poqun_yuefeng"],
	// 	img: "extension/破群杀/image/peipei.jpg",
	//  isZhugong: true,
	// },
	poqun_shaoye: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["poqun_yucheng", "poqun_quanduan", "poqun_quce"],
		img: "extension/破群杀/image/shaoye.jpg",
		isZhugong: true,
	},
	poqun_fengjie: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["poqun_fugui", "poqun_lingfeng"],
		img: "extension/破群杀/image/fengjie.jpg",
	},
	poqun_maolaoshi: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["poqun_zhiwei", "poqun_yunchou", "poqun_fengchun"],
		img: "extension/破群杀/image/maolaoshi.jpg",
	},
	poqun_xiaokong: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["poqun_lanxian", "poqun_juyi", "poqun_shengwei"],
		img: "extension/破群杀/image/xiaokong.jpg",
		isZhugong: true,
	},
	poqun_gule: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["poqun_guangyin", "poqun_jidou", "poqun_zhechong"],
		img: "extension/破群杀/image/gule.gif",
	},
	poqun_feichi: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["poqun_yiyu", "poqun_wangfu"],
		img: "extension/破群杀/image/feichi.jpg",
	},
	poqun_yikun: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["poqun_jihe", "poqun_chengyi"],
		img: "extension/破群杀/image/yikun.jpg",
		isZhugong: true,
	},
	poqun_xujiejie: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["huituo", "mingjian", "xingshuai"],
		img: "extension/破群杀/image/xujiejie.jpg",
		isZhugong: true,
	},
	poqun_xiwang: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["tiaoxin", "wangxi"],
		img: "extension/破群杀/image/xiwang.jpg",
		isZhugong: true,
	},
	poqun_xiwang_sp: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["poqun_qunxin", "poqun_fengchun"],
		img: "extension/破群杀/image/xiwang_sp.jpg",
		isZhugong: true,
	},
};

export default characters;
