const characters = {
	poqun_jiyi: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["poqun_rixun", "poqn_touxian", "poqun_yishen"],
		img: "extension/破群杀/image/jiyi.jpg",
	},
	poqun_xiaoche: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["poqun_leshi", "poqun_ziyu", "poqun_quuan"],
		img: "extension/破群杀/image/xiaoche.jpg",
	},
	poqun_xiaoqi: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["poqun_zhuanjie", "poqun_qianzong"],
		img: "extension/破群杀/image/xiaoqi.jpg",
	},
	poqun_lingxin: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["poqun_cangfeng", "poqun_huifeng"],
		img: "extension/破群杀/image/lingxin.jpg",
	},
	poqun_dadi: {
		sex: "male",
		group: "shu",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["poqun_bianlu", "poqun_daifa"],
		img: "extension/破群杀/image/dadi.jpg",
	},
	// poqun_peipei: {
	// 	sex: "female",
	// 	group: "qun",
	// 	hp: 3,
	// 	maxHp: 3,
	// 	hujia: 0,
	// 	skills: ["poqun_yucheng", "poqun_quanduan", "poqun_yuefeng"],
	// 	img: "extension/破群杀/image/peipei.jpg",
	// },
	poqun_shaoye: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["poqun_yucheng", "poqun_quanduan", "poqun_quce"],
		img: "extension/破群杀/image/shaoye.jpg",
	},
	poqun_fengjie: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["poqun_fugui", "poqun_lingfeng"],
		img: "extension/破群杀/image/fengjie.jpg",
	},
	poqun_maolaoshi: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["poqun_zhiwei", "poqun_yunchou", "poqun_fengchun"],
		img: "extension/破群杀/image/maolaoshi.jpg",
	},
};

export default characters;
